### ISSUE TITLE
PUT request for boat route

### ISSUE THREAD

**Issue by ValentaCodes** [ValentaCodes/DiveIn#36]
We need a PUT request in our boat api routes so we can update avaiiability  and renter_id

**Comment by MiahHub** [comment]
// new PUT route to update availability and renter id
router.put('/:id', async (req, res) => {
  try {
    const { availability, renterid } = req.body;
    const boat = await Boat.findByPk(req.params.id);
    const boatData = await boat.update({
      availability: availability,
      renterid: renterid,
    });
    res.status(200).json(boatData);
  } catch (err) {
    res.status(500).json(err);
  }
});

**Comment by MiahHub** [comment]
I have this working locally but wanted to discuss before pushing up.  Is this all we want to do for this function?

**Comment by ValentaCodes** [comment]
Hey thanks for reaching out! Yeah so we need the functionality of it
allowing a renter to reserve a boat and cancel a reservation if desired. If
it can do both those things then yeah it’s all we need. Also remember to
only add and push that file.

**Comment by MiahHub** [comment]
great, maybe we can discuss this during class?  I understand the concept, I would like to walk through the logic and triggers if we can.  Thanks as always!

**Comment by ValentaCodes** [comment]
Sounds good.
